### ISSUE TITLE
Help with using collections

### ISSUE THREAD

**Issue by rijulg** [microsoft/node-api-dotnet#124]
While trying to use collections I am running across errors like the following:
```
Class not registered for JS export: System.Collections.ObjectModel.ReadOnlyCollection`1[System.String]
Class not registered for JS export: System.Collections.Generic.List`1
Class not registered for JS export: System.Collections.ArrayList
```

I suspect I am doing something wrong, but a bit hard to find out what the correct process is, can you please help out?

Here's a snippet of my code (the full test project is available here: (https://github.com/rijulg/node-api-dotnet-issue)
```cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

public class HelloDll
{

    internal List<String> _items = new List<String>();
    public ReadOnlyCollection<String> items
    {
        get
        {
            return new ReadOnlyCollection<String>(_items);
        }
    }
    
    public void AddItem(string item)
    {
        _items.Add(item);
    }
}
```

```ts
import { Injectable } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { load as loadDLL } from "node-api-dotnet";

@Injectable()
export default class DLLRepository {
  private readonly helloClass: any;
  constructor(configService: ConfigService) {
    const dllPath = configService.getOrThrow("DLL_PATH");
    const dll = loadDLL(dllPath);
    this.helloClass = new dll.HelloDll();
  }
  addItem(item: string) {
    this.helloClass.AddItem(item);
  }
  getItems(): any {
    return this.helloClass.items;
  }
}

```
Calling `getItems` in JS fails.

**Comment by jasongin** [comment]
Hi, thanks for the issue report.

`ReadOnlyCollection<T>` and `IList<T>` are supposed to work in this kind of scenario, although `ArrayList` isn't currently supported. I will investigate and get back to you.

**Comment by jasongin** [comment]
Oh, you need to use the collection interfaces (`IReadOnlyCollection<T>` or `IList<T>`), instead of the classes (`ReadOnlyCollection<T>`, `List<T>`) on public properties consumed by JavaScript.

The classes may be supported later. But it's a good practice anyway to use collection interfaces for public properties.

**Comment by jasongin** [comment]
The relevant code is in `JSMarshaller.BuildFrom/ToJSCollectionExpressions()`. Going from .NET to JS (for a property `get`) should be a pretty small change, since the class can be handled exactly the same way as the interface. The opposite direction (for a property `set`) will be much more difficult, but maybe you don't need that.

You may find the code difficult to understand though, since it is building expression trees that then get either emitted at build time or compiled at runtime. I have been thinking about writing some technical documentation about how all of that works internally, but have not done it yet.

Your other alternative is to [build a .NET adapter](https://github.com/microsoft/node-api-dotnet/blob/main/Docs/node-module.md) for the JS interop layer.

**Comment by rijulg** [comment]
Thanks, I'll try both and share my findings here in either case.

**Comment by rijulg** [comment]
I tried using AOT process (building a .Net Adapater) but unfortunately the issue with classes and interfaces persists there. I will be trying to modify the library now to accommodate the missing classes. From my investigation so far I can tell that the classes are never exported because they are seen as `System` classes in `NodeApi.DotNetHost.AssemblyExporter.ExportClassDependencies`.  But based on Jason's feedback I'll try to modify the marshaller to export the classes.


For logkeeping I get the following error:

```log
Debug_String
[]
[ 0, 1, 2 ]
/home/workspace/workdir/srcext/js/main.js:14
    console.log(dll.TestBinding.listList);
                                ^

Error: Class not registered for JS export: System.Collections.Generic.List`1[System.Int32]
    at Microsoft.JavaScript.NodeApi.Interop.JSRuntimeContext.GetClassConstructor[T]()
    at Microsoft.JavaScript.NodeApi.Interop.JSRuntimeContext.<>c__DisplayClass28_0`1.<GetOrCreateObjectWrapper>g__CreateWrapper|0(T obj)
    at Microsoft.JavaScript.NodeApi.Interop.JSRuntimeContext.<>c__DisplayClass28_0`1.<GetOrCreateObjectWrapper>b__1(Object _)
    at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
    at Microsoft.JavaScript.NodeApi.Interop.JSRuntimeContext.GetOrCreateObjectWrapper[T](T obj)
    at Microsoft.JavaScript.NodeApi.Generated.Module.get_dotnet_TestBinding_listList(JSCallbackArgs __args) in /home/workspace/workdir/srcext/dotnet/Microsoft.JavaScript.NodeApi.Generator/Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator/dotnet.NodeApi.g.cs:line 63
    at Microsoft.JavaScript.NodeApi.JSNativeApi.InvokeCallback[TDescriptor](napi_env env, napi_callback_info callbackInfo, JSValueScopeType scopeType, Func`2 getCallbackDescriptor)
    at main (/home/workspace/workdir/srcext/js/main.js:14:33)
    at Object.<anonymous> (/home/workspace/workdir/srcext/js/main.js:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```


Here are the files I have
```cs
// /home/workspace/workdir/srcext/dotnet/TestBinding.cs
using Microsoft.JavaScript.NodeApi;

namespace dotnet;

[JSExport]
public class TestBinding
{
    public static List<int> listList { get; set; } = new List<int>(new int[] { 0, 1, 2 });
    public static IList<int> listIList { get; set; } = new List<int>(new int[] { 0, 1, 2 });
    public static int[] listArray { get; set; } = new int[] {0, 1, 2};
    public static string debugString { get; set; } = "Debug_String";
}
```
```cs
// /home/workspace/workdir/srcext/dotnet/dotnet.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.JavaScript.NodeApi" Version="0.2.26" />
    <PackageReference Include="Microsoft.JavaScript.NodeApi.Generator" Version="0.2.26" />
  </ItemGroup>

</Project>
```
```cs
// /home/workspace/workdir/srcext/dotnet/NuGet.Config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="local-packages" value="/home/workspace/workdir/node-api-dotnet/out/pkg" />
  </packageSources>
</configuration>
```
```js
// /home/workspace/workdir/srcext/js/main.js

const modPath = require.resolve("node-api-dotnet");
console.log(modPath);

const dotnet = require('node-api-dotnet');

function main() {
    const dllPath = process.argv[2];
    const dll = dotnet.require(dllPath);
    console.log(dll.TestBinding.debugString);
    console.log(dll.TestBinding.listIList);
    console.log(dll.TestBinding.listArray);
    console.log(dll.TestBinding.listList);
}

main()
```

Run process
```bash
cd /home/workspace/workdir/srcext/dotnet
dotnet build

cd /home/workspace/workdir/srcext/js
node main.js /home/workspace/workdir/srcext/dotnet/bin/Debug/net6.0/dotnet.dll
```

**Comment by jasongin** [comment]
The reason I suggested creating the .NET adapter module is so that you can precisely control the APIs that are exported to JavaScript, and therefore you can avoid any aspect of interop that is difficult or problematic. Even if you ultimately need to call a 3rd-party library that returns a concrete collection class like `ReadOnlyCollection<string>`, the public members of your adapter module can export it via the collection interface `IReadOnlyCollection<string>` instead of the class.

```C#
[JSExport]
public class HelloDllAdapter
{
    private readonly HelloDll instance = new();

    public IReadOnlyCollection<String> Items => instance.items;
}
```

**Comment by rijulg** [comment]
yes, that's a good point; I am just trying to adapt a large DLL almost automatically without having to write a lot of binding code. Will revert to other methods if fixing just a couple of collections is not enough.

**Comment by jasongin** [comment]
Closing in favor of #242 which has a more succinct description of the issue.
