### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by jasongin** [microsoft/node-api-dotnet#137]
So far, when projecting .NET APIs to JS, we have mostly been hiding the .NET namespaces. Instead, we map .NET assemblies to JS modules, and project all the assembly's public types as properties of the module. That assumes simple type name conflicts _within_ an assembly are rare.

Part of the reasoning for taking that approach was because namespaces are not widely used in JavaScript. While TypeScript has [support for namespaces](https://www.typescriptlang.org/docs/handbook/namespaces.html), [modules are generally the preferred way](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html) to organize public JavaScript APIs.

As we get into more complex capabilities and scenarios, there are more cases in which proper namespaces will make it easier and more natural to write JS code that works with .NET APIs. So I'm considering a full projection of .NET namespaces to TS namespaces. (Note TS "namespaces" are simply static objects and properties, so they can be used just as well from plain JS.)

There are at least two major advantages of fully projecting .NET namespaces to JS:
 - For complex APIs spanning multiple .NET assemblies, it is often not obvious which assembly contains a given type. The related assemblies use namespaces to provide more logical structure for related APIs, so referencing types by namespace is easier than referencing them by assembly. (The Node API assembly loader would merge shared namespaces from multiple assemblies.)
 - Working with generic APIs often requires specifying type names directly. The [current proposal for generics](https://github.com/microsoft/node-api-dotnet/issues/67#issuecomment-1534432346) suggests using **strings** for fully-qualified type names. But proper namespaces projected to TypeScript would avoid typos and allow for compiler-verified type references.

Of course, types could still be aliased to simple names, similar to a `using name = type` statement in C#:

<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>

```TypeScript
const DateTime = dotnet['System.DateTime'];
```

</td>
<td>

```TypeScript
const System = dotnet.System;
const DateTime = System.DateTime;
```

</td></tr>
</table>

**Comment by jasongin** [comment]
@vmoroz Do you have any comments?

**Comment by vmoroz** [comment]
Sounds good to me! While namespaces are not popular in TypeScript, they can clearly benefit the mappings of C# types to TypeScript.
