### ISSUE TITLE
Use a response file to pass long arguments list to the typedefs generator tool

### ISSUE THREAD

**Issue by ShortDevelopment** [microsoft/node-api-dotnet#148]
I'm trying to integrate node-api into a production asp.net core app that has a lot of reference assemblies.
It seems that the command that's executed (38_040 characters) is hitting the [maximum length](https://stackoverflow.com/a/28452546/15213858) of windows commands.

It might be beneficial to allow directories as input to the `--reference` parameter or create a temporary `*.txt` file for parameters like `CsWinRT` does:
https://github.com/microsoft/CsWinRT/blob/ab4eb3d08778aa49f1d4fde0c1bbf635733571a1/nuget/Microsoft.Windows.CsWinRT.targets#L187-L191

**Comment by jasongin** [comment]
I'm considering using the same response file format as `csc`:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/miscellaneous#responsefiles

**Comment by jasongin** [comment]
Published to nuget as version `0.4.22`.
