### ISSUE TITLE
Pushing alpha build to npm

### ISSUE THREAD

**Issue by rijulg** [microsoft/node-api-dotnet#150]
Hey Team,

While the project is in alpha, and I understand this may be for quite some time, can we start pushing the built modules to npm similar to how we are pushing the dotnet modules?

**Comment by jasongin** [comment]
@rijulg The `node-api-dotnet` package has been published to npm for a while and is updated with every release: https://www.npmjs.com/package/node-api-dotnet

Is there something you think is missing?

See the [node-api-dotnet/examples](https://github.com/microsoft/node-api-dotnet/tree/main/examples) directory for example uses of it. While those reference the locally-built package, the same should work using the package from npm.
