### ISSUE TITLE
AOT - Module did not self-register

### ISSUE THREAD

**Issue by figabytes** [microsoft/node-api-dotnet#171]
I am attempting to create a very simple "Hello World" C# project for AOT, following the documentation here [https://github.com/microsoft/node-api-dotnet/blob/main/Docs/node-module.md](url) 

The AOT module was created with the latest preview version of .NET 8.0.0-rc.2, using Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.8.0 Preview 6.0.  

I included the following packages and updated the project settings according to the docs:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <PublishNodeModule>true</PublishNodeModule>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.JavaScript.NodeApi" Version="0.4.18" PrivateAssets="all" />
    <PackageReference Include="Microsoft.JavaScript.NodeApi.Generator" Version="0.4.18" PrivateAssets="all" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
  </ItemGroup>

</Project>
```

Below is the only code in the project marked with the `JSExport` Attribute

```
using Microsoft.JavaScript.NodeApi;

namespace AotTest
{
    [JSExport]
    public class MyClass
    {
        public void Hello()
        {
            Console.WriteLine("Hello World from C# AOT!");
        }
    }
}
```
I was able to get it to compile and publish a _.node_ file and _.d.ts_ file which I referenced in a nodeJS TypeScript project.

However, when attempting to load the module, I receive the following error

>  node:internal/modules/cjs/loader:1327
>   return process.dlopen(module, path.toNamespacedPath(filename));
> 
> Error: Module did not self-register: 'full-path-to-aot-module\AotTest.node'.
>     at Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
>     at Module.load (node:internal/modules/cjs/loader:1091:32)
>     at Module._load (node:internal/modules/cjs/loader:938:12)
>     at Module.require (node:internal/modules/cjs/loader:1115:19)
>     at require (node:internal/modules/helpers:130:18)
>     at Object.<anonymous> 
>     ...
>   code: 'ERR_DLOPEN_FAILED'
> }
> 
> Node.js v20.9.0

**Comment by jasongin** [comment]
Are you able to run the [`aot-module`](https://github.com/microsoft/node-api-dotnet/tree/main/examples/aot-module) example project? It is very similar to what you have.

Check that the source-generator produced the module registration code. After the build you can find the generated `.g.cs` source file under `obj/Debug/net8.0/win0x64/generated/`, and it should have lines similar to this near the top, which should enable Node.js to register the module:
```C#
public static class Module
{
    [UnmanagedCallersOnly(EntryPoint = "napi_register_module_v1")]
    public static napi_value _Initialize(napi_env env, napi_value exports)
        => Initialize(env, exports);
```

In your `.csproj` file, try updating the `<PackageReference>` items to match how they are in the example. I'm not sure if your extra attributes there are causing a problem. (The documentation might be out of date.)

**Comment by figabytes** [comment]
Thanks for the feedback.  The generated `.g.cs` file was not being generated.  I tried the [example](https://github.com/microsoft/node-api-dotnet/blob/main/examples/aot-module/aot-module.csproj) project and was getting the same result.  In both cases, I was attempting to publish the project using the IDE, which produced a `.node` file but it would not register.  I decided to delete the publish profile created by the IDE and just run `dotnet publish` from the CLI, which correctly builds the module and allowed me to import the example project successfully in NodeJS.  

When I attempted to do the same thing in my test project, I had to specify a runtime identifier when publishing using `dotnet publish -r win-x64`.  I assume this is because the [example](https://github.com/microsoft/node-api-dotnet/blob/main/examples/aot-module/aot-module.csproj) project inherited this from the parent folder configuration.   Afterwards I was able to get it to work in my node app.  The only thing I had to change, was adding `//@ts-ignore` above the import because Typescript did not recognize the file as a module.

**Comment by jasongin** [comment]
> I was attempting to publish the project using the IDE

I haven't tried that; I don't know exactly what it does. The `.g.cs` file is generated by a [C# compiler source-generator](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) that should run during any build, independent of the publish step. So I don't understand why it wouldn't get generated when building/publishing from the IDE.

> The only thing I had to change, was adding //@ts-ignore above the import because Typescript did not recognize the file as a module.

It should be possible to get TypeScript type-definitions from importing the module, since a `.d.ts` is auto-generated also. That may depend on your project settings (commonjs vs ES modules) and the syntax used to import, so I'd need more info to troubleshoot.

**Comment by figabytes** [comment]
> I haven't tried that; I don't know exactly what it does. The `.g.cs` file is generated by a [C# compiler source-generator](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) that should run during any build, independent of the publish step. So I don't understand why it wouldn't get generated when building/publishing from the IDE.

I don't know the difference either.  I did a little research on the differences between `dotnet build`  and Visual Studio/MSBuild.  For the most part, they should produce the same result, but I did come across [this SO post](https://stackoverflow.com/questions/66349892/whats-the-difference-between-using-dotnet-and-msbuild-for-building-net-applica) claiming that Analyzers targeting .NET Core/.NET 5+ will only run from `dotnet build`, which might explain why NodeApi.Generator is not producing the generated code.  In fact, I have created a more complex project that compiles from Visual Studio, but throws errors from the CLI, so there is definitely something different about how the project is compiled.

Knowing there is at least a workaround by building and publishing from the CLI, I am going to close this issue.  

FYI, my main interest in this project is possibly having a better way to call Soap APIs from our Node application.  While there are several npm packages out there, I have not found an elegant solution for Soap in NodeJS/TypeScript.  I work with some very large third party Soap APIs with thousands of models and .NET is very good at generating client code using svcutil.exe.  I was hoping to be able to generate the client code that consumes these APIs and create C# projects that can be called from Node.

**Comment by jasongin** [comment]
> Analyzers targeting .NET Core/.NET 5+ will only run from dotnet build

Yes that would explain it: NodeApi.Generator is an analyzer (source-generator) that targets .NET 6 or later. I wasn't aware of that limitation of analyzers in VS. I assume it's because VS MSBuild runs on .NET Framework 4.x. We could investigate making the analyzer target .NET Standard 2.0 or .NET Framework to support that.

> I was hoping to be able to generate the client code that consumes these APIs and create C# projects that can be called from Node.

Interesting!
