### ISSUE TITLE
Cannot generate d.ts using dotnet 8.0

### ISSUE THREAD

**Issue by tsanyqudsi** [microsoft/node-api-dotnet#186]
In Readme.md it's written like this :

> ### Generate TS type definitions for .NET APIs
> If writing TypeScript, or type-checked JavaScript, there is a tool to generate type .d.ts type definitions for .NET APIs. It also generates a small .js file that makes it simple to load the assembly DLL and type-definitions together.
> 
> `$ npm exec node-api-dotnet-generator --assembly ExampleAssembly.dll --typedefs ExampleAssembly.d.ts`
> 
> ```
> // TypeScript
> import './ExampleAssembly.js'; // TS also loads the adjacent .d.ts file.
> dotnet.ExampleNamespace.ExampleClass.ExampleMethod(...args); // This call is type-checked!
> ```

However, when I'm trying to use it, it has this error

`You must install or update .NET to run this application.
App: /usr/bin/node
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /**redacted**/.dotnet
The following frameworks were found:
  8.0.0 at [/**redacted**/.dotnet/shared/Microsoft.NETCore.App]
Learn more:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=linux-x64&os=archcraft
/**redacted**/.npm/_npx/2fb4d186a11c44f3/node_modules/node-api-dotnet/init.js:32
  return nativeHost.initialize(targetFramework, managedHostPath, require);
                    ^
Error: Failed to inialize CLR host. Status: FrameworkMissingFailure`

Is this intended as in I have to install dotnet 6 or is it a bug ?

**Comment by jasongin** [comment]
The TS generator tool targets .NET 6 (so it can be used with that version), though I thought it should work also on .NET 8, without having .NET 6 installed. I'll look into this when I get a chance; for now yes you can workaround by installing .NET 6.

**Comment by jasongin** [comment]
Fixed with #215
