### ISSUE TITLE
byte[] from .NET becomes string in Node

### ISSUE THREAD

**Issue by james-hu** [microsoft/node-api-dotnet#206]
I am calling .NET from Node. 
There's a .NET method returning byte[]. In the generated type definition, the return type is Number[].
However, the actul data type of the object returned (`typeof x`) is 'string'.
Length of the string (number of characters in the string) is is shorter than the length of the byte array (number of elements in the array). I I've tried hacking into it, but I cound't find a way to convert the return value correctly to Buffer or byte array for consuming.

Is this a bug?

**Comment by jasongin** [comment]
Probably a bug. I think we don't have good tests for this scenario right now. I'll have to investigate.
