### ISSUE TITLE
Could not load type 'SkiaSharp.ISKSkipObjectRegistration' from assembly 'Micros oft.JavaScript.NodeApi.Generator.SymbolExtensions_1

### ISSUE THREAD

**Issue by alexey-butalov-aspose** [microsoft/node-api-dotnet#225]
Hello, 
I got the next exception while publishing a test project with AOT.

`
CSC : error NAPI1001: TypeLoadException : Could not load type 'SkiaSharp.ISKSkipObjectRegistration' from assembly 'Micros oft.JavaScript.NodeApi.Generator.SymbolExtensions_1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.   at System. Reflection.Emit.RuntimeTypeBuilder.CreateTypeNoLock()   at System.Reflection.Emit.RuntimeTypeBuilder.CreateTypeInfoImpl()    at Microsoft.JavaScript.NodeApi.Generator.SymbolExtensions.AsType(ITypeSymbol typeSymbol, Type[] genericTypeParameters , Boolean buildType)   at Microsoft.JavaScript.NodeApi.Generator.SymbolExtensions.AsType(ITypeSymbol typeSymbol, Type[] g enericTypeParameters, Boolean buildType)   at Microsoft.JavaScript.NodeApi.Generator.SymbolExtensions.BuildSymbolicMethod (TypeBuilder typeBuilder, IMethodSymbol methodSymbol, Type[] genericTypeParameters)   at Microsoft.JavaScript.NodeApi.Gen erator.SymbolExtensions.BuildSymbolicTypeMembers(ITypeSymbol typeSymbol, TypeBuilder typeBuilder, Type[] genericTypeParam eters)   at Microsoft.JavaScript.NodeApi.Generator.SymbolExtensions.BuildSymbolicObjectType(INamedTypeSymbol typeSymbol,  String typeFullName, Type[] genericTypeParameters, Boolean buildType)   at Microsoft.JavaScript.NodeApi.Generator.SymbolE xtensions.AsType(ITypeSymbol typeSymbol, Type[] genericTypeParameters, Boolean buildType)   at Microsoft.JavaScript.NodeA pi.Generator.SymbolExtensions.BuildSymbolicMethod(TypeBuilder typeBuilder, IMethodSymbol methodSymbol, Type[] genericType Parameters)   at Microsoft.JavaScript.NodeApi.Generator.SymbolExtensions.BuildSymbolicTypeMembers(ITypeSymbol typeSymbol,  TypeBuilder typeBuilder, Type[] genericTypeParameters) [X:\NodeJS\ConsoleApp1\ConsoleApp1.csproj]                                                                                                                             
`
Please find the sample project attached.
How to reproduce:
Unzip the attached project, run publish.cmd.
The issue can be related to #201 

net8, NodeApi 0.5.8, Windows 10 x64.
[ConsoleApp1.zip](https://github.com/microsoft/node-api-dotnet/files/14572507/ConsoleApp1.zip)

**Comment by jasongin** [comment]
Thanks for the bug report. With the provided sample project I was able to debug this issue and create a PR to fix it: #227

**Comment by jasongin** [comment]
Please try again with v0.5.12.

**Comment by alexey-butalov-aspose** [comment]
> Please try again with v0.5.12.
Thank you, it works now.
