### ISSUE TITLE
Marshalling: Collection classes like List<T>, Dictionary<T>, ReadOnlyCollection<T>

### ISSUE THREAD

**Issue by jasongin** [microsoft/node-api-dotnet#242]
.NET collection _interfaces_ like `IList<T>`, `IDictionary<T>`, `IEnumerable<T>` etc. are already supported for marshalling to/from JS collections. This issue is about adding support for marshalling collections where the property or parameter type is defined as a _class_ like `List<T>`, `Dictionary<T>`, or `ReadOnlyCollection<T>` instead of an interface.

Use of collection classes in public APIs is generally considered a bad practice:
 - [Why we don't recommend using List<T> in public APIs](https://learn.microsoft.com/en-us/archive/blogs/kcwalina/why-we-dont-recommend-using-listt-in-public-apis)
 - [CA1002 - Do not expose generic lists](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1002)

Still, a lot of code does this anyway, especially if the APIs are ultimately internal to an application and not part of a polished public SDK. So, it makes sense to have some support for marshalling collection classes.

Unfortunately there are some limitations that make efficient marshalling of collection classes difficult. While .NET collection interfaces are marshalled by reference (proxy) in both directions, classes cannot use the same approach because there is no way to fully override the implementation of `List<T>` or `Dictionary<T>` in a way that replaces the internal representation.

There was an attempt to implement this feature in #128, which stalled due to this challenge.

When revisiting this, we'll need to carefully consider the semantics for marshalling all variations of collections and arrays in .NET and JS and decide on an approach that is as consistent and efficient as possible, while dealing with some unavoidable compromises.

**Comment by rijulg** [comment]
Just a note on this issue considering I worked on the initial PR. I ultimately ended up extending the external dependency I wanted to support and improved typing on that which allowed me to circumvent having the collection support in the node-api-dotnet library.
