### ISSUE TITLE
Error when importing ES module

### ISSUE THREAD

**Issue by luanmm** [microsoft/node-api-dotnet#254]
I don't know if this is something new, but seems to be a behavioral change from the last versions. Maybe is related to ES modules (I'm using it because it is a true standard, not a Node-related definition like "CommonJS").

This is the  `package.json` for the script/module:

```json
{
  "name": "@project/test",
  "type": "module",
  "main": "./index.js"
}
```

This is the `index.js` script:

```js
import { EventEmitter } from "node:events";

const emitter = new EventEmitter();

emitter.on("test", (uuid) => {
  console.log("uuid", uuid);
});

export { emitter };
```

This is the .NET code:

```csharp
_node.Run(() =>
{
     var emitter = _node.Import("/path/to/script/package", "emitter", esModule: true);
     emitter.CallMethod("emit", "test", Guid.NewGuid().ToString("N"));
});
```

This is the error:

![Screenshot from 2024-04-01 15-32-50](https://github.com/microsoft/node-api-dotnet/assets/1708808/64dce1d4-bbb2-4034-92ac-737de542655d)

It should work, right? Or am I doing something wrong?

I'm using the last version (v0.6.3).

**Comment by jasongin** [comment]
It looks like there is a bug with importing a specific property from an ES module. I'll fix that. Meanwhile it should be possible to import the whole ES module as an object, then get the property separately.

But also ES module imports are asynchronous, so the `Import()` method returns a `JSPromise`. Use `await ImportAsync()` instead to get the async result.

This should work:

```C#
await _node.RunAsync(async () =>
{
    var emitterPackage = await ImportAsync("/path/to/script/package", "emitter", esModule: true);
    var emitter = emitterPackage["emitter"];
    emitter.CallMethod("emit", "test", Guid.NewGuid().ToString("N"));
});
```

I will write some documentation about importing JS modules into .NET when I get a chance.

**Comment by luanmm** [comment]
Thanks for the tips, Jason! I've tested here, but the `ImportAsync` never returns and does not throw anything, either. The only thing that is similar to an error is this line in logs:

```sh
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
```

Couldn't understand why, to be honest.

**Comment by luanmm** [comment]
That was the problem, indeed. Now, with `baseDir` being specified, it worked.

I would suggest two things, then (if I may):
- An exception could be thrown when a module is imported without `baseDir` being specified in environment (otherwise is a bit difficult to relate these things);
- The `baseDir` property could be described in more detail somewhere in docs, because it is not too clear why it is even needed - in my scenario, the `baseDir` has the very same value as the imported script/module path (both are specified as the directory of the `package.json`, because the script file is specified as the `main` property).

Just two points that may contribute (or not :smile:, maybe I missed something on how things are working here).

Thank you very much, @jasongin!

**Comment by jasongin** [comment]
> An exception could be thrown when a module is imported without baseDir being specified in environment

An exception _was_ thrown - that was the InvalidOperationException you saw in logs. I suspect somewhere in your application you are not awaiting the async Task result, so the exception was ignored.

The exception message would have been similar to the one you saw before:

> The import function was not found on the global node_api_dotnet object. Set global.node_api_dotnet.import before loading the module.

However that message does need updating. It currently assumes .NET was loaded from Node.js, not the other way around. To be more helpful it should say something about that `CreateEnvironment() baseDir` property.

> The baseDir property could be described in more detail somewhere in docs

Currently it is [documented in comments](https://github.com/microsoft/node-api-dotnet/blob/dbdbf87a4c14fe317e20a173ed2f023e6d20315e/src/NodeApi/Runtime/NodejsPlatform.cs#L79) on the method itself, but there's nothing more than that yet. I am [working on](https://github.com/microsoft/node-api-dotnet/commit/4e1bd45bb8aa68a3728504a79d335abd5e9498ec) a whole new docs site that will have a lot of updated and expanded content including a section about importing packages. It will eventually also include API docs generated from the doc-comments in the code.

I'm closing this issue since the problem was resolved, and I fixed the bug about importing the property in #257.

**Comment by luanmm** [comment]
> An exception _was_ thrown - that was the InvalidOperationException you saw in logs. I suspect somewhere in your application you are not awaiting the async Task result, so the exception was ignored.

Oh, makes sense! I can confirm now that this was the case :smile: I was using (just for simplicity of my tests) the constructor of a DI class, that could not `await` the runner. My bad!

> Currently it is [documented in comments](https://github.com/microsoft/node-api-dotnet/blob/dbdbf87a4c14fe317e20a173ed2f023e6d20315e/src/NodeApi/Runtime/NodejsPlatform.cs#L79) on the method itself, but there's nothing more than that yet. I am [working on](https://github.com/microsoft/node-api-dotnet/commit/4e1bd45bb8aa68a3728504a79d335abd5e9498ec) a whole new docs site that will have a lot of updated and expanded content including a section about importing packages. It will eventually also include API docs generated from the doc-comments in the code.

Very nice, @jasongin! Thanks for pointing out!

> I'm closing this issue since the problem was resolved, and I fixed the bug about importing the property in #257.

Sure. Thank you very much for all your effort and being so helpful regarding the Github issues too!

-----

Just a disclaimer: Please do not take anything that I'm writing here as criticism about the work from you or other developers/collaborators! I'm just suggesting things based on my own experience (and, sometimes, based on an improper way to work with the library). So, there are many things that I may suggest that could even be already present in codebase or documented somehow. If this is the case, please just ignore it.

**Comment by jasongin** [comment]
> Please do not take anything that I'm writing here as criticism

Not at all, the feedback is welcome! As this project is still in development, we're aware there are bugs, usability issues, and incomplete documentation. It is helpful to hear about where people are having challenges, so we know where to focus our efforts on improving things.
