### ISSUE TITLE
How to use it in electron?

### ISSUE THREAD

**Issue by 2kking** [microsoft/node-api-dotnet#256]
![image](https://github.com/microsoft/node-api-dotnet/assets/14724188/f8edfd4c-79e7-4563-9fa3-35d01b40349d)

**Comment by jasongin** [comment]
Which major version of .NET are you trying to load? Is that version installed on the system?

You can specify the version when importing the module, for example:
```JavavScript
const dotnet = require('node-api-dotnet/net8.0');
```
Currently the supported target framework monikers are net472, net6.0, and net8.0.

**Comment by 2kking** [comment]
Thank you, the issue has been resolved.
I have versions 4.72, 6.0, and 8.0 preview. It worked when specifying either 4.72 or 6.0. Reinstalling the latest version 8.0, also resolved the issue.
