### ISSUE TITLE
Node runtime error when working with DependencyInjection

### ISSUE THREAD

**Issue by Waleed-KH** [microsoft/node-api-dotnet#286]
A simple .Net Node Module with DependencyInjection reference produce runtime error

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^

Error: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishDir>bin\pkg</PublishDir>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.JavaScript.NodeApi" Version="0.7.8" />
		<PackageReference Include="Microsoft.JavaScript.NodeApi.Generator" Version="0.7.8" />
	</ItemGroup>
</Project>
```

```c#
using Microsoft.Extensions.DependencyInjection;
using Microsoft.JavaScript.NodeApi;

namespace NodeApiTest;

[JSExport]
public class MyServiceHost
{
	private readonly ServiceProvider _serviceProvider;

	public MyServiceHost()
	{
		var serviceCollection = new ServiceCollection();
		_serviceProvider = serviceCollection.BuildServiceProvider();
	}
}
```

```js
import { MyServiceHost } from "node-api-test";

const service = new MyServiceHost();
```

When enable `PublishAot` it works fine, but can't use it due to its limitations

.Net SDK v8.0.204 
Node.js v20.11.0

**Comment by jasongin** [comment]
Sorry I missed this issue when it was opened...

Try adding `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` to your `.csproj` file so that the missing assembly gets copied to the output directory where it should be found at runtime.

**Comment by Waleed-KH** [comment]
Still not working, the assembly `Microsoft.Extensions.DependencyInjection.Abstractions` gets copied to the output directory even without `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`, but still showing error at runtime

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^

Error: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

**Comment by P-de-Jong** [comment]
I'm running into this same problem running on Linux. When i explicitly load the `Microsoft.Extensions.DependencyInjection` dll like below, it does seem to work.

```ts
import dotnet from 'node-api-dotnet';
dotnet.load('/path-to-my-library/bin/Debug/net8.0/Microsoft.Extensions.DependencyInjection.dll');

```

When i load the `Microsoft.Extensions.DependencyInjection.Abstractions` dll instead, it throws the error for the `Microsoft.Extensions.DependencyInjection` dll.

**Comment by moriyalb** [comment]
> Still not working, the assembly `Microsoft.Extensions.DependencyInjection.Abstractions` gets copied to the output directory even without `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`, but still showing error at runtime
> 
> ```
> node:internal/process/esm_loader:34
>       internalBinding('errors').triggerUncaughtException(
>                                 ^
> 
> Error: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
> ```

try add below:

 dotnet.addListener('resolving', (name, version) => {
	 try{
		const filePath = path.join(__dirname, 'bin', name + '.dll');		 
		if (fs.existsSync(filePath)) {		
			 dotnet.load(filePath)
		 }
	 }catch(e){
		 console.log("Something happend. " , e)
	 }
 	
});

**Comment by CreativeManix** [comment]
I have same issue in linux, any workaround for this?

**Comment by jasongin** [comment]
I've investigated this and I have a plan to improve how assemblies can be automatically loaded from both .NET system directories and the application directory.

Until then, the `addListener('resolving')` workaround suggested above should work.

**Comment by jasongin** [comment]
Resolution of dependency assemblies should work much better now with version 0.8.1 or later, with no need to set up a `resolving` event handler in most cases.
