### ISSUE TITLE
Malformed regex in CJS loader on Linux/Mac

### ISSUE THREAD

**Issue by daniacedue** [microsoft/node-api-dotnet#287]
Hello,

When publishing a NAOT node package with dotnet utility on Linux or Mac, the Common JS loader for the library has a syntax error:
`const moduleName = path.basename(__filename, __filename.match(/(/.[cm]?js)?$/)[0]);`

On the other hand, when publishing on Windows, there is no error:
`const moduleName = path.basename(__filename, __filename.match(/(\.[cm]?js)?$/)[0]);`

Perhaps it has something to do with the generator using OS-dependent paths in regex (when it should not)?

Thanks

**Comment by jasongin** [comment]
Oh, that's odd. It seems to be some strange behavior of MSBuild `WriteLinesToFile`, which is used to [apply some transformations](https://github.com/microsoft/node-api-dotnet/blob/84c93fc8895048cc662a489c15671d59e8ddb7d3/src/NodeApi/NodeApi.targets#L25) to that file when publishing as AOT. I'll figure out a workaround.

**Comment by jasongin** [comment]
Yep, it's a bug in MSBuild: https://github.com/dotnet/msbuild/issues/3468
