### ISSUE TITLE
Does it support .NET 8 WinForms?

### ISSUE THREAD

**Issue by my-yy** [microsoft/node-api-dotnet#291]
Firstly, I'd like to express my appreciation for this fantastic project.
I'm encountering an issue while attempting to utilize a class from a .NET 8  WinForm project:  

C#:
```C#
[JSExport]
public class VanillaScreenCapture
{
    public static Bitmap takeFullScreenPicture()
    {
        int screenWidth = Screen.PrimaryScreen.Bounds.Width;
        int screenHeight = Screen.PrimaryScreen.Bounds.Height;
        Bitmap fullscreen_bitmap = new Bitmap(screenWidth, screenHeight, PixelFormat.Format32bppArgb);

        using (Graphics g = Graphics.FromImage(fullscreen_bitmap))
        {
            g.CopyFromScreen(0, 0, 0, 0, new Size(screenWidth, screenHeight), CopyPixelOperation.SourceCopy);
        }

        return fullscreen_bitmap;
    }
}
```

JS:

```Javascript
const dotnet = require('node-api-dotnet/net8.0');
const ExampleModule = dotnet.require('./net8.0-windows/WindowCaptrue');
console.log(ExampleModule.VanillaScreenCapture.takeFullScreenPicture())
```

When I call the C# class from JavaScript , it reported the following error:

```
const ExampleModule = dotnet.require('./net8.0-windows/WindowCaptrue');
                             ^

Error: ReflectionTypeLoad_LoadFailed
Could not load file or assembly 'System.Windows.Forms, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
Could not load file or assembly 'System.Windows.Forms, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'System.Drawing.Common, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

Could you please advise on how to address this issue? Thanks!

**Comment by jasongin** [comment]
I'm not sure why those assemblies are not resolved automatically. As a workaround you can explicitly load assemblies by name or path before they are used:

```JavaScript
const dotnet = require('node-api-dotnet/net8.0');
dotnet.load('System.Drawing.Common');
dotnet.load('System.Windows.Forms');
```

However once you resolve the assemblies then you'll encounter another problem:

> Error: Class not registered for JS export: System.Drawing.Bitmap

Only types defined by your assembly are "exported" to JS. So I'd recommend you save the image to a file. (Perhaps the file path would be provided by the JS caller.) Or save it to a `MemoryStream` and return the bytes as `Memory<byte>` which gets marshalled to JS as a `UInt8Array`.

Another alternative can be to use the [dynamic invocation approach](https://github.com/microsoft/node-api-dotnet/blob/main/Docs/dynamic-invoke.md), where you don't write any C# code. Then the JS code can directly work with the `Bitmap` class and other types in `System.Drawing` / `WinForms`.

**Comment by my-yy** [comment]
Thanks, It works!

**Comment by cedx** [comment]
Not luck on my side :cry:

I'm trying to port a PowerShell script using Windows Forms. This script works fine.
Cf. [gui.ps1](https://gist.github.com/cedx/fc379d01b5676a428a63f3197180b257#file-gui-ps1)

I've added the `System.Drawing.Common` assembly to the project file.
Cf. [gui.csproj](https://gist.github.com/cedx/fc379d01b5676a428a63f3197180b257#file-gui-csproj)

The build seems to work: the `dotnet build` does not trigger any error or warning.
But when I try to run the JS port, I get the following error: `TypeError: Point is not a constructor`
Cf. [gui.js](https://gist.github.com/cedx/fc379d01b5676a428a63f3197180b257#file-gui-js)

If I comment every line involving a `System.Drawing` type, everything works but, of course, the UI is unusable: all controls are positioned at point `(0, 0)`.

What did I miss?
Note: I know absolutely nothing about .NET development (I'm a pure Node.js developer).

**Comment by cedx** [comment]
A little improvement: I had forgotten to load the `System.Drawing.Primitives` assembly. But now I get the error:

```
Unhandled exception. System.MissingMethodException: Method not found: 'System.Drawing.SizeF System.Drawing.Graphics.MeasureString(System.String, System.Drawing.Font, Int32)'.
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception ex)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**Comment by cedx** [comment]
OK, finally fixed: the import order is very important.
The error was due to the `System.Drawing.Common` assembly being loaded before `System.Drawing.Primitives`.
