### ISSUE TITLE
Asp minimalAPI with node IPC 

### ISSUE THREAD

**Issue by PrestigeDevop** [microsoft/node-api-dotnet#301]
Hello , I was trying to build [polyglot-backend](https://github.com/PrestigeDevop/polyglot-backend?tab=readme-ov-file) as replacement of the Obsolete  [InodeService](https://www.c-sharpcorner.com/article/nodeservices-where-javascript-and-net-meet-back-on-the-other-side/) for web API . 

but it seems slightly hard because asp API changed a lot since .net 5 ( specially the scaffold / DI part) . 
is it possible - **intended** to expose node modules for asp endpoints ? 
for example I want to import -invoke QR code from minimal api - mvc  endpoints .

also where I can get prebuilt nodelib.dll so I can use it with unity engine directly - similar use cases but also equivalent for Tencent PureTS?

and does this help me export c# library to use in js ?! i.e using Semantic kernel in Fuseopen or Capacitor .js runtimes ?

**Comment by jasongin** [comment]
> is it possible - intended to expose node modules for asp endpoints ?
for example I want to import -invoke QR code from minimal api - mvc endpoints.

Yes it's possible. You can use this project to load and call node modules from .NET code. The [winui-fluid example project](https://github.com/microsoft/node-api-dotnet/tree/main/examples/winui-fluid) does that. While that is a desktop application, you could do the same from a .NET web service project.

> also where I can get prebuilt nodelib.dll so I can use it with unity engine directly

`libnode` binaries are not published yet but you can build your own. See https://github.com/microsoft/node-api-dotnet/issues/107#issuecomment-2057928923

> and does this help me export c# library to use in js ?! i.e using Semantic kernel

Yes. See the [semantic-kernel example project](https://github.com/microsoft/node-api-dotnet/tree/main/examples/semantic-kernel).

**Comment by jasongin** [comment]
Some new documentation is published at https://microsoft.github.io/node-api-dotnet/scenarios/dotnet-js.html

I'm closing this since I think the questions are answered now. Feel free to re-open this one, or open a new issue, if you have more questions.
