### ISSUE TITLE
Microsoft.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by diegoaraujolima** [microsoft/node-api-dotnet#308]
When loading a Class Library project that uses SqlClient, when we create a SqlConnection instance it reports the error:

Microsoft.Data.SqlClient is not supported on this platform

The problem does not occur when we use, for example, a Windows Forms project that uses this Class Library.

Test project:
https://github.com/diegoaraujolima/node-dotnet-api-sql

Note that I created a method to dynamically load the referenced assemblies so I don't need to load them on the node.

**Comment by GabrielPDVNet** [comment]
I also had this problem when trying to start directly:

dotnet.load(sDirDLLs + 'Microsoft.Data.SqlClient.dll');
        var sCon = new dotnet.Microsoft.Data.SqlClient.SqlConnection(
            "Data Source=localhost\database;Initial Catalog=test;Persist Security Info=True;User ID=sa;Password=*********;TrustServerCertificate=True;");

**Comment by diegoaraujolima** [comment]
I tried implementing Assembly resolve using the following examples:

```
dotnet.addListener('resolving', (name, version) => {
    const filePath = path.join(__dirname, 'bin', name + '.dll');
    if (fs.existsSync(filePath)) dotnet.load(filePath);
});
```

But the error happens the same way when creating a SqlConnection instance.

**Comment by jasongin** [comment]
I see some other people are hitting that error when trying to dynamically load Microsoft.Data.SqlClient in different ways. Do either of these solutions work for you?

https://stackoverflow.com/questions/62514719/microsoft-data-sqlclient-is-not-supported-on-this-platform-entity-framework-co
https://stackoverflow.com/questions/72559921/microsoft-data-sqlclient-is-not-supported-on-this-platform-in-net-6-0-c-sharp-l

Anyway I don't think it is an issue with node-api-dotnet.

**Comment by diegoaraujolima** [comment]
But the error only happens when I load an assembly through node-dotnet-api. If I load it using a console app, for example, it doesn't happen. Neither in debug nor in release.

**Comment by jasongin** [comment]
Add this line to your library project file:
```
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
```
This solution was in the second stack-overflow link I shared above. I verified it works using the example repo you provided.

**Comment by diegoaraujolima** [comment]
Yes, you're right. By setting it explicitly it worked. Thanks a lot for the help. However, now I'm getting a different error:

Globalization Invariant Mode is not supported

It's as if node-dotnet-api was running in a virtualized environment.

I tried using 'InvariantGlobalization=false' in runtimeconfig.json and also in .csproj, but it didn't work either.
