### ISSUE TITLE
How to call JS from .NET？

### ISSUE THREAD

**Issue by 526677804** [microsoft/node-api-dotnet#313]
1.Is the framework already supported, and to what extent? Is there any relevant documentation I can refer to?

2.the [winui-fluid example code](https://github.com/microsoft/node-api-dotnet/blob/main/examples/winui-fluid).libnode.dll How to get it？

-----
Hello, 
In my project, I need to call JS from .NET, but there is no complete path to refer to. I want to confirm the above two questions first.

**Comment by jasongin** [comment]
Embedding Node.js in a .NET application is still experimental, and there is not very good documentation for it yet, only [the section in the README](https://github.com/microsoft/node-api-dotnet?tab=readme-ov-file#load-and-call-javascript-packages-from-net), and the example code linked above. I am working on writing more docs.

`libnode` is not published, but you can build your own. See https://github.com/microsoft/node-api-dotnet/issues/107#issuecomment-2057928923

**Comment by jasongin** [comment]
I have some documentation about this in PR at https://github.com/microsoft/node-api-dotnet/pull/318/files?short_path=40fcb52#diff-40fcb526f85373b1bd3b53db8eeab6fd3eb07a2b99aa0f74c00cf53079d29855

**Comment by jasongin** [comment]
The doc is published at https://microsoft.github.io/node-api-dotnet/scenarios/dotnet-js.html
