### ISSUE TITLE
Impact of .NET and C# Version Usage

### ISSUE THREAD

**Issue by 526677804** [microsoft/node-api-dotnet#314]
.NET version: .NET Framework 4.7.1 or .NET Standard 2.1
C# version: 9.0
----
I understand that the library has limited versions.But the .NET version is also limited in the Unity project, as shown above.

I use this library in my unity project, but there are many problems in the access, and I am trying to solve them. The current problems are mainly related to the C# language version, such as namespaces within the file scope and global using instructions. But I am not sure whether this path can be run in the end, so please tell me whether I should continue to try? Or are there other paths to try?

**Comment by jasongin** [comment]
I'm not sure I understand the problem. You should reference `Microsoft.JavaScript.NodeApi` as a nuget package reference, so the language version used to build that package (currently C# 12) should not matter. Your C# 9 project should be able to reference and use the nuget package regardless of the language version the package was built with.

When you reference the nuget package, MSBuild should automatically choose the correct target framework version from the package. It currently supports the following target frameworks:
 - .NET Framework 4.7.2
 - .NET Standard 2.0
 - .NET 6
 - .NET 8

You mentioned .NET Framework 4.7.1, which I guess is just barely too old. Is that the problem? Are you able to update your project to .NET Framework 4.7.2? I am not experienced with Unity development so I don't know what the requirements or limitations are there.

**Comment by jasongin** [comment]
If you're still experiencing this problem, can you share the error messages from the build?
