### ISSUE TITLE
How to export custom class objects on the C# side？

### ISSUE THREAD

**Issue by 526677804** [microsoft/node-api-dotnet#317]
Hello, I try to export the custom class object on the C# side and use it on the JS side.

But in reality, the object cannot be used on the JS side.The content is as follows：

C#：
` ExampleModule.csproj

    [JSExport]
    public class TestObj{
        public int fieldInt = 10;

        public string fieldStr = "ABC";

        public int[] fieldIntArray = new int[5] { 99, 98, 92, 97, 95 };

        public Dictionary<string, string> fieldDict = new Dictionary<string, string>(){
        {"UK", "London, Manchester, Birmingham"},
        {"USA", "Chicago, New York, Washington"},
        {"India", "Mumbai, New Delhi, Pune"}
        };

        public List<int> fieldList = new List<int> { 1, 2, 3, 4, 5, };
    }

    public static class Test{
        public static TestObj obj = new TestObj();

        public static TestObj HelloObj(string objId)
        {
            TestObj objInternal = new TestObj();

            objInternal.fieldStr = objId;

            return objInternal;
         }

    }
`

JS：
![image](https://github.com/microsoft/node-api-dotnet/assets/44428270/eaefdbea-539f-4dfe-a863-9ec7cf695e09)

----
‘export the custom class object on the C# side and use it on the JS side.’
Is this usage allowed?What is the correct way to use it?

In addition, my complete business scenario is as follows：
1.C#：class A: { public custom_class getObj() { return new custom_class(); }
2.JS->C#：obj = module.A.getObj()
3.JS：obj.property.value = new_value;
4.C#：bool result = obj.property.value == new_value;  **result = true;**

Can this library cover this case?

**Comment by jasongin** [comment]
Class fields are [not yet supported](https://github.com/microsoft/node-api-dotnet/issues/63). Use properties instead.

Also add `[JSExport]` to your `Test` class.

**Comment by 526677804** [comment]
Thanks!

Hi, I made the adjustments as you suggested.Halfway to success, the basic properties are OK, but the collection is not.

The content is as follows：

C#
`
[JSExport]
public class TestObj{
    public int fieldInt = 10;

    public string fieldStr = "ABC";

    public int[] fieldIntArray = new int[5] { 99, 98, 92, 97, 95 };

    public Dictionary<string, string> fieldDict = new Dictionary<string, string>(){
    {"UK", "London, Manchester, Birmingham"},
    {"USA", "Chicago, New York, Washington"},
    {"India", "Mumbai, New Delhi, Pune"}
    };

    public List<int> fieldList = new List<int> { 1, 2, 3, 4, 5, };
}

[JSExport]
public static class Test{
    public static TestObj obj = new TestObj();

    public static TestObj HelloObj(string objId)
    {
        TestObj objInternal = new TestObj();

        objInternal.fieldStr = objId;

        return objInternal;
     }

}
`

**Comment by jasongin** [comment]
APIs exported to JavaScript must use collection interfaces like `IDictionary<,>` and `IList<>`.

The collection classes like `Dictionary<,>` and `List<>` are [not yet supported](https://github.com/microsoft/node-api-dotnet/issues/242).

Also I wrote some new documentation about arrays and collections, which is in PR now:
https://github.com/microsoft/node-api-dotnet/pull/318/files#diff-c64aafac9f6a2f7bbea81287e5deaad004e3cf68d8b7ce4bd02e87d39c82d034

**Comment by 526677804** [comment]
Thx!

I made the changes according to your suggestions, but I still cannot use the collection functions from C# normally on the JS side, such as viewing, modifying (error reporting), etc.

The content is as follows：

C#：
` ExampleModule.csproj

    [JSExport]
    public class TestObj{
        public int fieldInt { get; set; } = 10;

        public string fieldStr { get; set; } = "ABC";

        public int[] fieldArray { get; set; } = new int[5] { 99, 98, 92, 97, 95 };

        public IDictionary<string, string> fieldDict { get; set; } = new Dictionary<string, string>(){
        {"UK", "London, Manchester, Birmingham"},
        {"USA", "Chicago, New York, Washington"},
        {"India", "Mumbai, New Delhi, Pune"}
        };

        public IList<int> fieldList { get; set; } = new List<int> { 1, 2, 3, 4, 5, };
    }


    public static class Test{
        public static TestObj obj { get; set; } = new TestObj();

        public static TestObj HelloObj(string objId)
        {
            TestObj objInternal = new TestObj();

            objInternal.fieldStr = objId;

            return objInternal;
         }

    }
`
C# build：
![image](https://github.com/microsoft/node-api-dotnet/assets/44428270/0e3dd661-63c9-4bad-b819-96ef87c9f7bf)



JS：
![e5a516f0-6068-4bbc-8cf7-e362a7140e61](https://github.com/microsoft/node-api-dotnet/assets/44428270/567bed0f-c597-44ab-8846-a598453ca561)

-----
Is collection usage allowed? What is the correct way to use it?

**Comment by jasongin** [comment]
It is almost working. You can write JavaScript code now to use the collections:

```JS
const ExampleModuleObj = ExampleModule.Test.obj;

const list = ExampleModuleObj.fieldList; // Array<number>
console.log(`list length: ${list.length}`);
console.log(`list items: ${list.join()}`);

const dict = ExampleModuleObj.fieldDict; // Map<string, string>
console.log(`dict size: ${dict.size}`);
console.log(`dict items: ${[... dict.entries().join(';')]}`);
```

The debugger accurately shows that the collection instances on the JavaScript side are technically [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) objects. The JS/.NET marshaller automatically sets up the collection proxies so that any access to the collections on the JavaScript side gets _proxied_ over to the .NET side.

If you have TypeScript type definitions set up correctly, VS Code type hints should show that `fieldList` is of type `Array<number>` and `fieldDict` is of type `Map<string, string>`. The collection proxies provide a simulation of those JavaScript types.

However, while checking this I just found there is a bug in the list proxy code, so it always returns `undefined` for the list items. I just created PR #319 to fix that.

**Comment by 526677804** [comment]
I improved my previous comment, and I tried your latest reply and still have the problem.

JS：
![image](https://github.com/microsoft/node-api-dotnet/assets/44428270/13d9fed7-ca98-4805-9f41-89471dbc7f00)

**Comment by jasongin** [comment]
> It is recommended to have complete examples on how to use collection on the JS side and C#, which will save a lot of time

This project is still in development, so do not expect everything to be working perfectly or fully documented yet. I just added a lot of documentation in #318. I will try to add some collection examples too.

> Is there a time plan or where can I track this information?

Simple PRs are usually merged within a few days. After every PR is merged, the build, test, release, and publish to NuGet are automatic and usually complete in around 2 hours.

**Comment by jasongin** [comment]
> TypeError: dict.entries.join is not a function

Oh, sorry I had a mistake in my example code. The `]` was in the wrong place. It should be:

```JavaScript
console.log(`dict items: ${[... dict.entries()].join(';')}`);
```

**Comment by 526677804** [comment]
I tried to modify the IDictionary object obtained from the C# side on the JS side. The modification can be perceived in C#. The following is a test, and it is found that the set interface of the JS map cannot be used.

C#
`
    public static void HelloPrintCollection()
    {
        System.Console.WriteLine($"[C#] HelloPrintCollection! start!");

        foreach (KeyValuePair<string, string> kvp in obj.fieldDict)
        {
            Console.WriteLine("Key = {0}, Value = {1}", kvp.Key, kvp.Value);
        }

        System.Console.WriteLine($"[C#] HelloPrintCollection! end!");
    }
`

JS:
![image](https://github.com/microsoft/node-api-dotnet/assets/44428270/f71e7dd1-d2de-4ceb-8106-f7693426082b)

**Comment by jasongin** [comment]
> the set interface of the JS map cannot be used

I updated PR #319 to also fix that bug with the Map proxy.

The PR is merged, however release to NuGet is blocked by an unrelated build infrastructure issue. We're working on that.

**Comment by jasongin** [comment]
Version `0.7.26` is published to NuGet.
