### ISSUE TITLE
How to use streaming across .NET and JS？

### ISSUE THREAD

**Issue by 526677804** [microsoft/node-api-dotnet#320]
![image](https://github.com/microsoft/node-api-dotnet/assets/44428270/051cbf99-4579-4c28-8aeb-d9e6b870e535)
----
See tips on streaming usage on the home page, but I couldn't find any detailed documentation.
I want to try this method, so I will confirm a few questions in advance.

1. Is there any relevant usage documentation?
2. Can this usage cover the actual usage scenarios in this problem? [#317](https://github.com/microsoft/node-api-dotnet/issues/317)

**Comment by jasongin** [comment]
There is some test code:
 - https://github.com/microsoft/node-api-dotnet/blob/main/test/TestCases/napi-dotnet/streams.js
 - https://github.com/microsoft/node-api-dotnet/blob/main/test/TestCases/napi-dotnet/Streams.cs

But otherwise no further documentation or examples yet.
