### ISSUE TITLE
Syntax errors in generated files 

### ISSUE THREAD

**Issue by camnewnham** [microsoft/node-api-dotnet#329]
Hello,
I've encountered a few syntax errors resulting in the generated typescript files causing them not to parse correctly. I'm generating on a third party / non-mutable dll.
![image](https://github.com/user-attachments/assets/c3c68992-0973-4f7a-8dd6-0d4a66a02a91)

I can manually go and edit the generated file, but would it be possible to sanitize the comments before writing them?

**Comment by jasongin** [comment]
Can you share the doc-comment XML element for `ReportDeferredContentAndFile`? I'm trying to understand where that extra `*/` came from.

**Comment by jasongin** [comment]
Never mind, I found it the [RhinoCommon](https://www.nuget.org/packages/RhinoCommon) nuget package.

```xml
<member name="M:Rhino.Render.RenderContentSerializer.ReportDeferredContentAndFile(Rhino.Render.RenderContent,System.String,System.Int32)">
    <summary>
    This is called from your implementation of LoadMultiple() to add a 'deferred' content and the
    file it will be loaded from when the LoadMultipleFlags.Preload flag is set.
    See LoadMultiple() for an explanation of this method's use.
    \param c is the deferred content.
    \param wszFullPath is the full path to the file that 'c' will be loaded from.
    \param flags is reserved for future use; you should pass zero.
    \param pReserved is reserved for future use; you should pass nullptr. */
    </summary>
    <param name="renderContent">
    Deferred render content - represents all contents that will be loaded from the file.
    </param>
    <param name="pathToFile">
    Full path of the file that render contents will be loaded from.
    </param>
    <param name="flags">
    Flags for future use; should be passed as zero.
    </param>
    <since>7.0</since>
</member>
```

The extra `*/` shows up [in their HTML documentation too](https://developer.rhino3d.com/api/rhinocommon/rhino.render.rendercontentserializer/reportdeferredcontentandfile).

I guess there's not much to do about it other than have the generator strip any `*/` that are found in the xmldoc content.
