### ISSUE TITLE
How to use project reference 

### ISSUE THREAD

**Issue by niltor** [microsoft/node-api-dotnet#336]
I want to publish a node command line tool, but I have already implemented the core functions in .net, so now I want to call my class library through node.

I created a new csproj project to reference my class library project, and after dotnet build, I did not find the .js file of my project. The project is like:

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutDir>./bin</OutDir>
        <NodeApiAssemblyJSModuleType>esm</NodeApiAssemblyJSModuleType>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.JavaScript.NodeApi.Generator" Version="0.7.31" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\NodeInterop\NodeInterop.csproj" />
    </ItemGroup>
</Project>

```

After 'dotnet build'...

`NodeInterop` is the classLib what I want to use in js. but I can't find `NodeInterop.js` in `bin` dir, so 
how can I use it?

**Comment by jasongin** [comment]
Try adding `<GenerateNodeApiTypeDefinitionsForReferences>true</GenerateNodeApiTypeDefinitionsForReferences>` to your project properties. It is supposed to be enabled automatically when the project is empty (no `.cs` files) but maybe something is preventing that.

MSBuild properties reference: https://microsoft.github.io/node-api-dotnet/reference/msbuild-props.html

**Comment by niltor** [comment]
> Try adding `<GenerateNodeApiTypeDefinitionsForReferences>true</GenerateNodeApiTypeDefinitionsForReferences>` to your project properties. It is supposed to be enabled automatically when the project is empty (no `.cs` files) but maybe something is preventing that.
> 
> MSBuild properties reference: https://microsoft.github.io/node-api-dotnet/reference/msbuild-props.html

Not working!  The `PackageReference` can be generated .js file, but `ProjectReference` does not!

**Comment by jasongin** [comment]
I looked into this and found it was not working how I expected. So in #339 I have fixed the MSBuild targets and added an example project.
