### ISSUE TITLE
JSExport On ExpandoObject Will Cause VS2022 Compiler Stuck

### ISSUE THREAD

**Issue by moriyalb** [microsoft/node-api-dotnet#351]
`
    [JSExport]
	public class Test
	{
		public ExpandoObject eo;
	}`

And VS2022 Compiles will never stop……（can be canceled）， no error reported。

**Comment by jasongin** [comment]
Thanks for the bug report, I'll investigate.

**Comment by jasongin** [comment]
#356 fixes the hang.

However `ExpandoObject` is probably not going to work well anyway. If the goal is to work with an arbitrary JavaScript value or object, use `JSValue` or `JSObject` instead. See also https://microsoft.github.io/node-api-dotnet/features/js-types-in-dotnet.html
