### ISSUE TITLE
Handling 'Multiple overloads were found for the supplied argument types (Number)'

### ISSUE THREAD

**Issue by camnewnham** [microsoft/node-api-dotnet#352]
I noticed that trying to use methods that have JS-similar parameters (i.e. float vs double both are number) I get this (title) overload error.  https://github.com/microsoft/node-api-dotnet/blob/d52ad7c8e438d34fd07808e97e2a809396c2dc0a/src/NodeApi/Interop/JSCallbackOverload.cs#L231-L232

Is there any technique I can use to skip the export of a 'duplicate' or to simply call the first available instead?

Example class:

```C# 
    public class Point
    {
        public double X { get; set; }

        public void Add(float y)
        {
            X += y;
        }
        public void Add(double y)
        {
            X += y;
        }
    }
``` 

----

This is also exhibited by functions that take structs as inputs (based on https://github.com/microsoft/node-api-dotnet/issues/347) when they share the same properties - unable to differentiate between a Point3f (float) and Point3d (double) when initializing as plain old javascript objects i.e. `{ X:1, Y:2, Z:3 }`

**Comment by jasongin** [comment]
This is a known limitation tracked by #134 

I have some ideas about how it could be handled better, but it hasn't been a top priority.

**Comment by jasongin** [comment]
I suppose in the specific case of choosing among overloads with numeric types, it should prefer the type with more precision: `double` over `float`. That would be relatively easy to fix, compared to a more general solution for providing an overload resolution hint.

**Comment by camnewnham** [comment]
Thankyou for adding support for struct constructors in https://github.com/microsoft/node-api-dotnet/pull/354 ! And the type overloads.

Would it be possible to use the [type from the constructor](https://github.com/microsoft/node-api-dotnet/issues/346#issuecomment-2264866893) to determine which method to invoke?

**Comment by jasongin** [comment]
Yes, that is what I meant in #134 by "the overload resolution logic will need to examine the actual class of object supplied, when necessary to select a distinct overload". It can get complicated though when considering subclasses, interfaces, and generics.

**Comment by jasongin** [comment]
I've made progress on this, I have it mostly working, there are just a few more special cases I need to handle before it's ready for PR.
