### ISSUE TITLE
In Dotnet How do i call JSON.parse in the node envirotnment

### ISSUE THREAD

**Issue by maxfridbe** [microsoft/node-api-dotnet#362]
I have tried var value = Jsonvalue.Global["JSON"] and tried running parse on that which crashes.

**Comment by jasongin** [comment]
What is the exception? Are you running it on the NodejsEnvironment thread?

This code worked for me:

```C#
using NodejsEnvironment nodejs = nodejsPlatform.CreateEnvironment();
nodejs.Run(() =>
{
    JSValue parseResult = JSValue.Global["JSON"].CallMethod(
        "parse", "{\"test\": \"Hello from JSON!\"}");
    Assert.Equal("Hello from JSON!", (string)parseResult["test"]);
});
```

**Comment by maxfridbe** [comment]
Yes thank you!, I had found .Global but was using it wrong.  I would highly recommend this to go into your examples folder
