### ISSUE TITLE
Generated code references undefined nested delegate type variable

### ISSUE THREAD

**Issue by moriyalb** [microsoft/node-api-dotnet#375]
`var type_jj_Jex_Runtime_DAdapter = new JSClassBuilder<object>("DAdapter")
	.AddProperty("JSRemoteCB", type_jj_Jex_Runtime_DAdapter_JSRemoteCB, JSPropertyAttributes.Static | JSPropertyAttributes.Enumerable)
				`

\Debug\net8.0\generated\Microsoft.JavaScript.NodeApi.Generator\Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator\DualJex.NodeApi.g.cs(34,32,34,71): error CS0103: 当前上下文中不存在名称“type_jj_Jex_Runtime_DAdapter_JSRemoteCB”

when I change to 0.8.3 , everything is ok.

**Comment by jasongin** [comment]
Thanks for the bug report. This is a regression related to nested delegate types. I just submitted PR #376 to fix it.
