### ISSUE TITLE
TypedArray / Memory<T> marshalling fails in Electron due to disabled external buffers

### ISSUE THREAD

**Issue by jasongin** [microsoft/node-api-dotnet#384]
I'm creating this issue to continue the discussion from https://github.com/microsoft/node-api-dotnet/pull/15#issuecomment-2381078420

Attempting to work with JS TypedArrays from C# may result in an error from Electron's flavor of Node:

> External buffers are not allowed: Error in CreateExternalArrayBuffer at D:\a\1\s\src\NodeApi\JSValue.cs:264

More information about the limitation is at https://github.com/electron/electron/issues/35801. This appears to be quite a controversial issue, but the Electron team seems to believe the limitation is necessary for security.

As a workaround, node-api-dotnet probably will need to handle the [new `napi_no_external_buffers_allowed` status code](https://github.com/nodejs/node/pull/45181) and fall back to copying the memory instead of using external buffers. That's very unfortunate since it can have a major performance impact in some scenarios, and doesn't have the same semantics as shared memory.

**Comment by jasongin** [comment]
Duplicate of #383

**Comment by Hiwen** [comment]
I think this discussion is very necessary, even if we copy the memory once and convert memory directly to a typed array, theoretically we can also achieve better performance.
