### ISSUE TITLE
Consider adding `<StripSymbols>true</StripSymbols>` to `PublishAot` projects

### ISSUE THREAD

**Issue by MichalStrehovsky** [microsoft/node-api-dotnet#49]
Noticed the following in the README.md: "Larger due to building necessary runtime code - minimum 3 MB on Windows, ~13 MB on Linux"

The 13 MB number on Linux is likely because the size includes debugging symbols. Consider guiding size-conscious users towards the [documented](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/#native-debug-information) switch to place debugging symbols into a separate file with `<StripSymbols>true</StripSymbols>`.

Btw, you can also remove `<NativeLib>shared</NativeLib>` - it's the default and [deliberately made so](https://github.com/dotnet/runtime/pull/70879).

**Comment by jasongin** [comment]
@MichalStrehovsky Thanks for the suggestions! I see that with StripSymbols=true, the symbols are still available in a separate `.dbg` file, so I guess we can then make them available separately. (Do symbol servers support it?)

I'm curious, what is your interest in this project, or how did you find it? I see you're on the .NET team - do you work on .NET Native AOT?

**Comment by MichalStrehovsky** [comment]
`StripSymbols` will add a [gnu debuglink](https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html) note to the executable, so debuggers will be aware that symbols can be found elsewhere. I don't know much about symbol servers. Native AOT executables also specify build id that should help finding the right symbols (build id also described in the linked doc). Just wanted to point it out since size seems to be at least of note based on the readme of this project.

I saw this project in a [tweet](https://twitter.com/_h0x0d_/status/1640528440544690178). And yep, I work on Native AOT.

**Comment by jasongin** [comment]
Yes, binary size is a concern, because to have a good JS deployment experience we have to bundle all the native binaries for supported platforms/architectures (8-10 total) into one npm package. Otherwise the package install has to download binaries for the current platform, which is often troublesome.

We're still working on setting up packaging & publishing pipelines, so we don't have such cross-platform packages available yet.

I'll experiment with stripping symbols on Linux soon.

**Comment by jasongin** [comment]
@MichalStrehovsky You might be interested in something else clever (crazy?) this project is doing with Native AOT. We use AOT C# code to [bootstrap the .NET runtime using `HostFxr`](https://github.com/microsoft/node-api-dotnet/blob/main/src/NodeApi/DotNetHost/NativeHost.cs) or `mscoree` [(PR)](https://github.com/microsoft/node-api-dotnet/blob/1c76768f4eb2da8ace58b9867d834828040e226c/src/NodeApi/DotNetHost/MSCorEE.cs) APIs. That way we don't have to deal with building a shim in another language like C++, and we can share some JS interop code between native and managed hosts.

**Comment by MichalStrehovsky** [comment]
That is indeed interesting!
