### ISSUE TITLE
Fix test-results reporting for PR builds from repo forks

### ISSUE THREAD

**Issue by jasongin** [microsoft/node-api-dotnet#71]
Currently PR builds appear to fail for any PR from a fork of the project repo, because the "Publish test results" step fails. The basic test results are still visible in the build logs, but the nice HTML results report doesn't succeed.

A solution is described at https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories

**Comment by vmoroz** [comment]
Let me look at it, since I am working on implementing CI scripts.
It should also help me implementing tests in the ADO CI builds.
